### ISSUE TITLE
Error on setup AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by filikun** [tybritten/ical-sensor-homeassistant#121]
When trying to setup a Google calendar I get the following error in HA. I use the secret url from the Google calendar as the url. The calendar is shared between me and the family but is not the one auto-generated by Google. I have two other Google calendar´s from the same account and they are working just fine.

```yaml
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/config/custom_components/ical/calendar.py", line 74, in async_update
    await self.ical_events.update()
  File "/config/custom_components/ical/__init__.py", line 139, in update
    self.calendar = self._ical_parser(
  File "/config/custom_components/ical/__init__.py", line 172, in _ical_parser
    if "UNTIL" in rrule:
  File "/usr/local/lib/python3.10/site-packages/icalendar/caselessdict.py", line 89, in __eq__
    return self is other or dict(self.items()) == dict(other.items())
AttributeError: 'str' object has no attribute 'items'
```

**Comment by Olen** [comment]
A beta release that should fix this is now available: [v1.10.0b1](https://github.com/tybritten/ical-sensor-homeassistant/releases/tag/v1.10.0b1)

The manual RRULE parsing code (where this crash occurred) has been completely replaced with the `recurring-ical-events` library, which handles RRULE expansion correctly.

To test: in HACS, enable "Show beta versions" in the download dialog and select `v1.10.0b1`. Feedback welcome.
