### ISSUE TITLE
Error when trying to setup ical platform for sensor

### ISSUE THREAD

**Issue by CaptainSweatpants** [tybritten/ical-sensor-homeassistant#125]
This just started about a week ago. 

Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.2
Frontend 20230608.0 - latest

`Logger: homeassistant.components.sensor
Source: custom_components/ical/__init__.py:135 
Integration: Sensor (documentation, issues) 
First occurred: 10:28:29 AM (1 occurrences) 
Last logged: 10:28:29 AM

Error while setting up ical platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 339, in parts
    validate_token(name)
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token
    raise ValueError(name)
ValueError: <!doctype html><html dir="ltr"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="description" content="Log into injixo. The first WFM solution for call centers in the cloud."/><title>injixo</title><link rel="icon" href="/app/favicon.ico"><script defer="defer" src="/app/runtime.9563b1.min.js"></script><script defer="defer" src="/app/vendor.f05e88.min.js"></script><script defer="defer" src="/app/main.7547a3.min.js"></script><link href="/app/styles.673eb1.css" rel="stylesheet"></head><body><div id="app"></div></body></html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ical/sensor.py", line 47, in async_setup_entry
    await ical_events.update()
  File "/config/custom_components/ical/__init__.py", line 135, in update
    event_list = icalendar.Calendar.from_ical(text.replace("\x00", ""))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 328, in from_ical
    name, params, vals = line.parts()
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 351, in parts
    raise ValueError(
ValueError: Content line could not be parsed into parts: '<!doctype html><html dir="ltr"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="description" content="Log into injixo. The first WFM solution for call centers in the cloud."/><title>injixo</title><link rel="icon" href="/app/favicon.ico"><script defer="defer" src="/app/runtime.9563b1.min.js"></script><script defer="defer" src="/app/vendor.f05e88.min.js"></script><script defer="defer" src="/app/main.7547a3.min.js"></script><link href="/app/styles.673eb1.css" rel="stylesheet"></head><body><div id="app"></div></body></html>': <!doctype html><html dir="ltr"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="description" content="Log into injixo. The first WFM solution for call centers in the cloud."/><title>injixo</title><link rel="icon" href="/app/favicon.ico"><script defer="defer" src="/app/runtime.9563b1.min.js"></script><script defer="defer" src="/app/vendor.f05e88.min.js"></script><script defer="defer" src="/app/main.7547a3.min.js"></script><link href="/app/styles.673eb1.css" rel="stylesheet"></head><body><div id="app"></div></body></html>
`

Any ideas what broke?

**Comment by tybritten** [comment]
That value error looks like the format of your feed changed. try using `wget` or `curl` on the url for your calendar feed and see if its in the proper ical format.

**Comment by CaptainSweatpants** [comment]
Forgive my lack of Linux understanding.So, to check for the ical validation i used icalendar.org’s ical validator and it returned 
File Size: 549 lines, 15910 bytes
Number of events found: 75
Number of timezones found: 1
Success! No errors found. 

I also have no issues importing this ical calendar URL with any of my other email platforms such as AppleMail or Outlook.
