### ISSUE TITLE
Errors - Unable to retrieve new events

### ISSUE THREAD

**Issue by lux4rd0** [tybritten/ical-sensor-homeassistant#136]
It looks like some more errors are keeping this integration from working. _(I've removed a few small pieces of the links just in case they contain credential details...)_

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:356
integration: Sensor (documentation, issues)
First occurred: May 9, 2024 at 8:54:20 PM (3 occurrences)
Last logged: 8:23:07 AM

Error while setting up ical platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 339, in parts
    validate_token(name)
  File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 128, in validate_token
    raise ValueError(name)
ValueError: <!doctype html><html lang="en-US" dir="ltr"><head><base href="https://accounts.google.com/v3/signin/"><link ref="preconnect" href="//www.gstatic.com"><meta name="referrer" content="origin"><style data-href="https://www.gstatic.com/_/mss/boq-identity/_/ss/" nonce="*****-vcpQ">c-wiz{contain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ical/sensor.py", line 47, in async_setup_entry
    await ical_events.update()
  File "/config/custom_components/ical/__init__.py", line 135, in update
    event_list = icalendar.Calendar.from_ical(text.replace("\x00", ""))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/icalendar/cal.py", line 328, in from_ical
    name, params, vals = line.parts()
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 353, in parts
    raise ValueError(
ValueError: Content line could not be parsed into parts: '<!doctype html><html lang="en-US" dir="ltr"><head><base href="https://accounts.google.com/v3/signin/"><link ref="preconnect" href="//www.gstatic.com"><meta name="referrer" content="origin"><style data-href="https://www.gstatic.com/_/mss/boq-identity/_/ss/k=boq-identity.AccountsSignInUi.ABkTD_qXXg8.L.X.O/am=*****/d=1/ed=1/rs=AOaEmlHYBF1fXyuUjF9NyFn7t8_vN2Tsvw/m=identifierview,_b,_tp" nonce="*****-vcpQ">c-wiz{contain:style}c-wiz>c-data{display:none}c-wiz.rETSD{contain:none}c-
```

**Comment by tybritten** [comment]
It appears to be an issue with your sign-in to google, its not returning the calendar feed but a html page for sign in it looks like.

**Comment by lux4rd0** [comment]
@tybritten - you're right - I went to redo the integration because it wasn't showing any events, and I used the wrong URL. Google has a "Secret address in iCal format" that I needed to use. All good now! Thanks for the nudge!
