### ISSUE TITLE
2024.6.0: Detected blocking call to open inside the event loop by custom integration 'ical'

### ISSUE THREAD

**Issue by golles** [tybritten/ical-sensor-homeassistant#137]
See blog post: https://developers.home-assistant.io/blog/2024/05/19/fix_zoneinfo_blocking_io/

```
2024-06-05 22:15:06.572 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'ical' at custom_components/ical/__init__.py, line 424: indate = indate.replace(tzinfo=gettz(str(indate.tzinfo))) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/tybritten/ical-sensor-homeassistant/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/ical/sensor.py", line 47, in async_setup_entry
    await ical_events.update()
  File "/config/custom_components/ical/__init__.py", line 139, in update
    self.calendar = self._ical_parser(
  File "/config/custom_components/ical/__init__.py", line 332, in _ical_parser
    dtstart = self._ical_date_fixer(
  File "/config/custom_components/ical/__init__.py", line 424, in _ical_date_fixer
    indate = indate.replace(tzinfo=gettz(str(indate.tzinfo)))
```

**Comment by tybritten** [comment]
I'll take a look

**Comment by N3rdix** [comment]
Resolved with https://github.com/tybritten/ical-sensor-homeassistant/pull/145
