### ISSUE TITLE
Blocking call to zoneinfo

### ISSUE THREAD

**Issue by psic4t** [tybritten/ical-sensor-homeassistant#143]
With HA 2024.06 I got the following in logs:

```
homeassistant    | 2024-09-12 10:33:09.726 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args
('/usr/share/zoneinfo/Europe/Berlin', 'rb') inside the event loop by custom integration 'ical' at custom_components/ical/__init__.py, line 419: indate = indate.replace(tzinfo=gettz(str(timezone))) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/tybritten/ical-sensor-homeassistant/issues
homeassistant    | For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "<frozen runpy>", line 198, in _run_module_as_main
homeassistant    |   File "<frozen runpy>", line 88, in _run_code
homeassistant    |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
homeassistant    |     sys.exit(main())
homeassistant    |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
homeassistant    |     exit_code = runner.run(runtime_conf)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
homeassistant    |     return loop.run_until_complete(setup_and_run_hass(runtime_config))
homeassistant    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
homeassistant    |     self.run_forever()
homeassistant    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
homeassistant    |     self._run_once()
homeassistant    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
homeassistant    |     handle._run()
homeassistant    |   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
homeassistant    |     self._context.run(self._callback, *self._args)
homeassistant    |   File "/config/custom_components/ical/sensor.py", line 47, in async_setup_entry
homeassistant    |     await ical_events.update()
homeassistant    |   File "/config/custom_components/ical/__init__.py", line 139, in update
homeassistant    |     self.calendar = self._ical_parser(
homeassistant    |   File "/config/custom_components/ical/__init__.py", line 332, in _ical_parser
homeassistant    |     dtstart = self._ical_date_fixer(
homeassistant    |   File "/config/custom_components/ical/__init__.py", line 419, in _ical_date_fixer
homeassistant    |     indate = indate.replace(tzinfo=gettz(str(timezone)))
```

**Comment by tybritten** [comment]
What timezone are you using?

**Comment by N3rdix** [comment]
Should be resolved already, fix was in https://github.com/tybritten/ical-sensor-homeassistant/pull/145
