### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Martinvdm** [tybritten/ical-sensor-homeassistant#18]
I do got Some errors often:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 441, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ical/sensor.py", line 151, in update
    self.data_object.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ical/sensor.py", line 195, in update
    events = dateparser(cal, today)
  File "/config/custom_components/ical/sensor.py", line 62, in dateparser
    start = arrow.get(event['DTSTART'].dt)
  File "/usr/local/lib/python3.7/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/arrow/factory.py", line 193, in get
    return self.type.fromdatetime(arg)
  File "/usr/local/lib/python3.7/site-packages/arrow/arrow.py", line 220, in fromdatetime
    tzinfo,
  File "/usr/local/lib/python3.7/site-packages/arrow/arrow.py", line 71, in __init__
    tzinfo = parser.TzinfoParser.parse(tzinfo.zone)
  File "/usr/local/lib/python3.7/site-packages/arrow/parser.py", line 380, in parse
    raise ParserError('Could not parse timezone expression "{}"'.format(string))
arrow.parser.ParserError: Could not parse timezone expression "Customized Time Zone"
```

**Comment by Olen** [comment]
Yeah, I got the same. It might be related to a change I made a little while back.

Doing various testing now to verify a fix.

**Comment by Olen** [comment]
Found another issue with the previous fix.  Timezones are difficult to handle.

Going to push another PR soon.

**Comment by Olen** [comment]
I believe this is fixed now
