### ISSUE TITLE
Owncloud/Nextcloud ICS

### ISSUE THREAD

**Issue by 1337hium** [tybritten/ical-sensor-homeassistant#4]
Hi, when i try to import the Calendar from my Nextcloud installation i get the following error:

`17-02-27 22:05:37 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ical
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.homeassistant/custom_components/sensor/ical.py", line 38, in setup_platform
    data_object.update()
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/root/.homeassistant/custom_components/sensor/ical.py", line 126, in update
    events = dateparser(cal,today)
  File "/root/.homeassistant/custom_components/sensor/ical.py", line 59, in dateparser
    if type(event['DTEND'].dt) is dt.date:
  File "/usr/local/lib/python3.5/dist-packages/icalendar/caselessdict.py", line 45, in __getitem__
    return super(CaselessDict, self).__getitem__(key.upper())
KeyError: 'DTEND'`

Any chance to avoid this?

**Comment by vmtyler** [comment]
what does your configuration.yaml look like for ical?

**Comment by 1337hium** [comment]
my configuration.yaml looks like this
`- platform: ical
   name: "Private"
   url: "https://url.to/cal.ics"
`

And the ICS



`BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Allgemein
X-APPLE-CALENDAR-COLOR:#FF7A66
BEGIN:VTIMEZONE
TZID:Europe/Zurich
X-LIC-LOCATION:Europe/Zurich
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/Belgrade
X-LIC-LOCATION:Europe/Belgrade
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Zurich:20160806T160000
SUMMARY:Pizzaessen
TRANSP:OPAQUE
STATUS:CONFIRMED
DTEND;TZID=Europe/Zurich:20160806T220000
LAST-MODIFIED:20160721T073651Z
DTSTAMP:20160721T073651Z
CREATED:20160721T073651Z
UID:005ab77c-fa39-4cc5-b1cd-0a210cf56054.1469086611483
END:VEVENT
`
