### ISSUE TITLE
RRULES errors after last update

### ISSUE THREAD

**Issue by Martinvdm** [tybritten/ical-sensor-homeassistant#40]
Hi,

Again this component fails with a lot of errors after the latest update and integration by UI instead of yaml.
Once you solved this in #23 , but now the same errors are returned.

I did try to use the same sensor.py, as you provided earlier, but this time it isn't helping.

Logging:
```
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in async_setup_entry,
    platform = await async_prepare_setup_platform(,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_prepare_setup_platform,
    platform = integration.get_platform(domain),
  File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform,
    cache[full_name] = self._import_platform(platform_name),
  File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform,
    return importlib.import_module(f"{self.pkg_path}.{platform_name}"),
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module,
  File "<frozen importlib._bootstrap_external>", line 916, in get_code,
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/config/custom_components/ical/sensor.py", line 7,
    <!DOCTYPE html>,
    ^,
SyntaxError: invalid syntax,
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-21 13:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 28, 12, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['TH'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-22 08:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 29, 7, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['FR'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-23 12:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 30, 11, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['SA'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted]- Start: 2021-01-25 08:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 25, 7, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['MO'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-26 06:30:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 26, 5, 30, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['TU'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-26 08:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 26, 7, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['TU'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-26 09:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 26, 8, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['TU'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-26 13:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 26, 12, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['TU'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-26 20:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 26, 19, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['TU'], 'WKST': ['MO']}),
2021-01-24 16:22:40 ERROR (MainThread) [custom_components.ical] Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: [redacted] - Start: 2021-01-30 09:45:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2021, 1, 30, 8, 45, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [6], 'BYDAY': ['SA'], 'WKST': ['MO']}),
```

**Comment by Martinvdm** [comment]
@Olen  do you know if there is any newer sensor.py with your fix of #23 i can use?

**Comment by Olen** [comment]
TImezones in python....
Turns out that the icalendar parser only accepts pytc.utc or dateutil.tzutc, but dateutil set the timezone to the tzfile-format.

```
>>> import datetime
>>> from dateutil.tz import tzutc, gettz
>>> dt = datetime.time(6, 15, 30, 999999, gettz("UTC")) 
>>> dt.tzinfo == tzutc
False
>>> tzutc
<class 'dateutil.tz.tz.tzutc'>
>>> dt.tzinfo
tzfile('/usr/share/zoneinfo/UTC')

```

Pushing a fix that changes utc timezones to tzutc. I don't think it should cause any issues with calendar entries that are sent as utc, and it seems to work fine here.

**Comment by Martinvdm** [comment]
@Olen thanks! So this issue is not the same as in #23 ? And your fix is fixing this issue?

**Comment by Olen** [comment]
Well. They are related, but the whole component has been rewritten since #23.
The problem is that the different components and modules use and require different formats for the timezone definition, and when they don't match, things don't work as expected.
So I tried to create a single function to set the _same_ tz-format for all cases, but then of course it turns out that rrule until does not understand that format...

WIth the latest PR, at least all my calendars are showing and updating again, and I don't get any rrule-errors in the logs

**Comment by Martinvdm** [comment]
Ok I understand. Issue in this calendar file is that there are no RRULES at all, it seems that Office 365 isn’t using that, as this iCal is from that source. Perhaps it is better to user and ‘if’ statement for RRULES and ‘else’ if it is not present.
