### ISSUE TITLE
24:00:00 isn't a valid time

### ISSUE THREAD

**Issue by IanAdd** [tybritten/ical-sensor-homeassistant#68]
Any chance you can use a valid or even better - user definable start and end times for all-day events you find.
```
Start January 12, 2022, 24:00:00
End January 13, 2022, 24:00:00
```
Valid times run from 00:00:00 - 23:59.59

**Comment by Olen** [comment]
I have never seen a calendar entry that goes to (or from) 24:00:00.
All full day events in my calendar starts at 00:00:00 on the day of the event and ends on 00:00:00 the next day.

And it it not a valid date format in python:
```
>>> time.strptime("00:00", "%H:%M")
time.struct_time(tm_year=1900, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=1, tm_isdst=-1)
```

```
>>> time.strptime("24:00", "%H:%M")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib64/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '24:00' does not match format '%H:%M'
```

**Comment by IanAdd** [comment]
![24](https://user-images.githubusercontent.com/10492213/148848794-95bc6403-6c81-4191-a6bb-e0a5c8431963.png)
The sensor created by the ical add-in shows this if you click on it and show its attributes.

**Comment by IanAdd** [comment]
Possibly relevant log entry....
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 09:57:59 (4 occurrences)
Last logged: 09:58:28

Entity calendar.ical_ha (<class 'custom_components.ical.calendar.ICalCalendarEventDevice'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by IanAdd** [comment]
Further update - suggesting it might not be ical at work...

Entities card as this..
```
title: Next Bookings
type: entities
entities:
  - type: attribute
    entity: calendar.airbnb
    attribute: message
    name: AB msg
  - type: attribute
    entity: calendar.airbnb
    attribute: start_time
```
Shows ...
![24_a](https://user-images.githubusercontent.com/10492213/148854676-e5524e89-7004-467e-ad9d-b15a40f33c10.png)

But developer tools page shows:
![24_b](https://user-images.githubusercontent.com/10492213/148854741-9d18c6b7-ae6e-4404-bf0d-59e667843af7.png)

Totally confused.

**Comment by IanAdd** [comment]
A similar HA system (without ical installed) with exactly the same link to the same google calendar returns the correct time.
I am going to revert to a backup pre 'ical' install and see if that is the cause.
![24_c](https://user-images.githubusercontent.com/10492213/148856786-6fc4aaa9-843a-42b5-87bb-1c378297a979.png)
