### ISSUE TITLE
ical is not visible in Home Assistant

### ISSUE THREAD

**Issue by lskierka** [tybritten/ical-sensor-homeassistant#88]
Hello,
I added ical integrations via hacs but I don't see this in home assistant integrations. 
I tried to add manually and also can't add this integration via UI. What am I doing wrong ?

**Comment by Olen** [comment]
After adding it in HACS you need to restart HA for the new integration to show up.
It should then be visible in the "Set up new integration" popup:

![image](https://user-images.githubusercontent.com/203184/163128538-d1f53ef3-afe2-437c-941f-2eba2ecc76d5.png)

**Comment by lskierka** [comment]
I restarted my home assistant but I can't find this component. 
I found one line in logs about it:
` We found a custom integration ical which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by Olen** [comment]
What version of Home Assistant is this?
That dialog is different from the one I see.

**Comment by lskierka** [comment]
Sorry, I used translator, because I using other language in my home assistant. In English language this dialog looks like that: 
![image](https://user-images.githubusercontent.com/27443574/163135919-02902168-ff85-481b-8ccc-1d4a151beab8.png)

My HA ver:
![image](https://user-images.githubusercontent.com/27443574/163136126-a45d4c0f-caa8-429f-ae8a-8a4530ef2fd4.png)

**Comment by Olen** [comment]
Ah, ok.

Do you see it in HACS?
What version does it say in HACS?
Do you have any other logs regarding the ical integration?

**Comment by lskierka** [comment]
I have HACS ver. 1.24.4. 
I see ical in hacs. 
![image](https://user-images.githubusercontent.com/27443574/163139102-9bdfadd2-c01c-4b15-ad9a-d207dc959c25.png)

This is full log: 
`2022-04-13 09:55:38 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ical which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-13 09:55:38 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration bodymiscale which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-13 09:55:38 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-13 09:55:38 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-13 09:55:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547882761664] Received invalid command: energy/get_prefs
2022-04-13 09:55:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547872420912] Received invalid command: mobile_app/push_notification_channel
2022-04-13 09:56:32 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 192, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 190, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
result = await self._async_handle_step(flow, flow.init_step, data, init_done)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/usr/src/homeassistant/homeassistant/components/yamaha_musiccast/config_flow.py", line 89, in async_step_ssdp
if not await MusicCastDevice.check_yamaha_ssdp(
File "/usr/local/lib/python3.9/site-packages/aiomusiccast/musiccast_device.py", line 87, in check_yamaha_ssdp
res = await client.get(location)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
message, payload = await protocol.read() # type: ignore[union-attr]
File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
2022-04-13 10:07:37 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Mi Air Purifier 3/3H data
2022-04-13 10:09:17 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Mi Air Purifier 3/3H data
2022-04-13 10:10:31 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Mi Air Purifier 3/3H data
2022-04-13 10:13:25 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Mi Air Purifier 3/3H data
2022-04-13 10:16:54 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Mi Air Purifier 3/3H data
2022-04-13 10:40:58 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Mi Air Purifier 3/3H data`

I have the same worring with BLE_monitor, but I can see it. 
Now I see the same problem with bodymiscale  :( I can't see it.

**Comment by Olen** [comment]
I see that some people are suggesting clearing the cache and doing a hard reload n the browser might solve the issue of custom components not showing up after installing via HACS.

**Comment by lskierka** [comment]
OMG, thanks. Now working.

**Comment by Olen** [comment]
Good to hear

**Comment by phillipsawyer** [comment]
OMG indeed! Was bashing my head over this for an hour
